### ISSUE TITLE
Missing first next occurrence

### ISSUE THREAD

**Issue by litinoveweedle** [buglss/node-red-clone-inject-with-cronti#14]
Hello,

this printscreen was captures today - 7/20/2023, with selected cron pattern (first day of the month) next occurrence shall be 8/1/2023, while the node is displaying hint of first next trigger to be scheduled at 9/1/2023. The problem is not only in in the hint display, but most importantly in the scheduler - no event is generated. I observed this issue with both 2.2.2 and 2.2.3 versions

Could there be an issue with the CEST timezone being used?

![image](https://github.com/buglss/node-red-crontinject/assets/15144712/284b8f8b-b62a-49a7-a0f2-398eb2e5a0c6)

**Comment by buglss** [comment]
@litinoveweedle Thank you for feedback. I'll be interested as soon as possible.

**Comment by buglss** [comment]
The reason for this problem was in the calculation function in the [cronjo](https://www.npmjs.com/package/cronjo) package of the occurrence time. I fixed the calculation function.

The commit id is 0248519b1399f89264dc1684bd02779b9f9ea151 of this issue. The [cronjo](https://www.npmjs.com/package/cronjo) package commit id is a0a8cb636674c72015b3de7f8c485eab3db87964.
