### ISSUE TITLE
Two out when job triggered

### ISSUE THREAD

**Issue by buglss** [buglss/node-red-clone-inject-with-cronti#6]
### [EN]
It's not a constant case. Detailed examination is required.

### [TR]
Sürekli rastlanan bir durum değil. Detaylı inceleme yapılması gerekiyor.

**Comment by buglss** [comment]
### [EN]
This situation was not found. It may be an exceptional situation.

### [TR]
Bu duruma rastlanmadı. Münferit olabilir.

**Comment by d21d3q** [comment]
I managed to reproduce it.  

It seems that when you play around with crojnjob value some instances are not cleaned up. 

1. Setup cronjob to `0 * * * *`
2. deploy
3. change pattern to `1 * * * *` (alter only one character)
4. defocus (click with mouse outside of pattern field so that "next events" are updated)
5. change pattern to '0 * * * *' 
6. defocus
7. change pattern to `* * * * *` 
8. deploy

`foo` has been set to `* * * * *` immediately, `bar` has been altered few times

![obraz](https://user-images.githubusercontent.com/490844/211516338-809c6e03-bc3a-4c17-b87e-c25e18e039fa.png)

![obraz](https://user-images.githubusercontent.com/490844/211516518-eb360950-8105-4f29-a200-f00e1f5e641f.png)

I used to have one instance of croninject that repeated output 5 times.

**Comment by buglss** [comment]
@d21d3q Ok thanks. I'll look into the example you give. I will try to solve it shortly.

**Comment by buglss** [comment]
## [TR]

Bu hataya bağımlılık paketi olan cronjo sebep olmuş. Planlanlamaların iptali ilk tetiklemeden sonra mümkün olmuyordu. Hata giderildi. (https://github.com/buglss/cronjo/issues/5)

**Dikkat**: 2.2.2 versiyonunda daha eski versiyonlar kullanılmamalıdır!

----

## [EN]

This error was caused by the dependency package cronjo. It was not possible to cancel the schedules after the first trigger. Bug fixed. (https://github.com/buglss/cronjo/issues/5)

**Caution**: Older versions must not be used in version 2.2.2!
